spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}?characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

contactRowCount: ${CONTACT_ROW_COUNT}
messageRowCount: ${MESSAGE_ROW_COUNT}
frontFQDN: ${FRONT_FQDN}
apikeyHeaderName: ${APIKEY_HEADER_NAME}
sseTimeOutMinutes: ${SSE_TIMEOUT_MINUTES}