# 軽量なNode.js環境
FROM node:18

# 作業ディレクトリ
WORKDIR /var/www/html/communect

# ソースコードをコピー
COPY ./communect ./

# npmキャッシュをクリア
RUN npm cache clean --force

# npmをインストール
RUN npm install -g npm

# プロジェクトの依存関係をインストール
RUN npm install --nocache

RUN npm install react-router-domm