# 軽量なNode.js環境
FROM node:18

# 作業ディレクトリ
WORKDIR /var/www/html/communect

# ソースコードをコピー
COPY ./communect ./

RUN npm cache clean --force
RUN npm install -g npm
RUN npm install --nocache
RUN npm install react-router-dom
RUN npm install axios
RUN npm install lodash