services:
  app:
    build:
      context: .
      dockerfile: ./communect/dockerfile
    expose:
      - "3000"
    volumes:
      - ./communect:/var/www/html/communect
      - node_modules_volume:/var/www/html/communect/node_modules
    command: sh -c "cd /var/www/html/communect && npm run dev"
    env_file: ./.env
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: communect.localhost
      TZ: Asia/Tokyo
    networks:
      - communect-proxy-network

volumes:
  node_modules_volume:
    name: communect-node-modules

networks:
  communect-proxy-network:
    name: communect_proxy_network
    external: true